import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import record from '../data/music.json'
import { useState, useEffect } from 'react';
import Router, { useRouter } from 'next/router';


export default function AlbumList() {
  console.log(record);
  const router = useRouter();

  // const [photos, setPhotos] = useState([]);
  // const [title, setTitle] = useState('');
  // const [description, setDescription] = useState('');
  // const [isFlipped, setFlipped] = useState(false);
  // const [images, setImages] = useState([]);  
  // const [image, setImage] = useState('');
  // const [name, setName] = useState({});
  // const [price, setPrice] = useState();

  const [hoveredIndex, setHoveredIndex] = useState(null);
  const [searchTerm, setSearchTerm] = useState('');


  useEffect(() => {
    const fetchImages = async () => {
      const res = await fetch('/music.json');
      const data = await res.json();
      setImages(data);
    };
    fetchImages();
  }, []);

  const handleMouseEnter = (index) => {
    setHoveredIndex(index);
  };
  const handleMouseLeave = () => {
    setHoveredIndex(null);
  };

  function handleClick() {
    router.push('/');
  };



  return (
    <>
      <Head>
        <title>Albums</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/kkhead.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Unbounded:wght@500&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Shrikhand&display=swap" rel="stylesheet" />
      </Head>
      <main className={styles.main}>

        <div className={styles.header1}><h1>Demo: K.K. House</h1></div>
        <div >
          <iframe className={styles.wrapperVideo}
            // width="560"
            // height="315"
            src="https://www.youtube.com/embed/0E1yOijtIaM"
            title="YouTube video player"
            frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            allowfullscreen>
          </iframe>
        </div>

        <div className={styles.header1}><h1>Playlist</h1></div>

        <div className={styles.wrapper}>

          {
            record.map((rec, index) => {
              return (
                <div key={rec.id} className={styles.container}>

                  <img src={rec.albumImage} className={styles.Image}
                    onMouseEnter={() => handleMouseEnter(index)} />


                  {hoveredIndex === index && (
                    <div className={styles.notePara}>
                      <p>{rec.sourcesNote}</p>
                    </div>
                  )}


                  <div className={styles.musicName}>{rec.Name}</div>
                  <div className={styles.musicAndPrice}>
                    <div className={styles.musicPrice}>Price: {rec.Buy}</div>
                    <Image src="/bells.png" className={styles.bellIcon} width="100" height="100" />
                  </div>

                </div>
              )
            })
          }

        </div>

        <div onClick={handleClick} className={styles.header2}>
          <h2>Go back</h2>
        </div>

      </main>
    </>
  )
}
