import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import record from '../data/music.json'
import { useState, useEffect } from 'react';
import Router, { useRouter } from 'next/router';
import Nintento from '../components/animation.js';


export default function Home() {

  const router = useRouter();
  const [image, setImage] = useState('');
  const [name, setName] = useState({});
  const [price, setPrice] = useState();

  function handleClick() {
    router.push('/albums');
  };


  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Unbounded:wght@500&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Shrikhand&display=swap" rel="stylesheet" />
      </Head>

      <main className={styles.main}>
      <div className={styles.header1}><h1>Hey there</h1></div>
        <Nintento></Nintento>

        <div onClick={handleClick} className={styles.header2}>
          <h2>See Albums</h2>
        </div>

      </main>
    </>
  );
}

